Feat/8410 button component
Altinn/altinn-design-system pull request #22
Opened 2022-05-24 14:49 UTC by mjulstein

Early review (not ready for merge.)
Input on code direction would be nice.
And holding off doc for now.

2022-05-25 05:28 UTC, haakemon requested changes

2022-05-30 09:52 UTC, mjulstein commented on src/components/Button/Button.module.css
> +.button {
👍

2022-05-30 09:53 UTC, mjulstein commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
My guess is that it is to make The button text centered. (Used the padding from figma)

2022-05-30 09:57 UTC, mjulstein commented on src/components/Button/Button.module.css
> +  outline-offset: -1px;
The outline is practically in place for the border here. The benefit of using outline as the border is that it doesn't affect the box model. Visually it is used as a border, but outline is used for it's benefit in this case.

2022-05-30 10:00 UTC, haakemon commented on src/components/Button/Button.module.css
> +  outline-offset: -1px;
But shouldnt it use the token variable instead of a fixed value (1px)?

2022-05-30 10:34 UTC, mjulstein commented on src/components/Button/Button.module.css
> +  outline-offset: -1px;
Yes :)

2022-06-01 06:20 UTC, mrosvik commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
@haakemon  Beklager, har ikke sett dette før nå. Ja, det er riktig @mjulstein , ulik padding på top og bottom slik at teksten sentreres basert på høyden til versalene.

2022-06-01 06:20 UTC, mrosvik commented on src/components/Button/Button.module.css
> +  outline-offset: -1px;
Mulig jeg har glemt å legge dette inn som en token-verdi.

2022-06-01 06:37 UTC, mrosvik commented on src/components/Button/Button.module.css
> +  outline-offset: -1px;
Oppdatert nå @mjulstein 
![image](https://user-images.githubusercontent.com/1464915/171342704-40219523-711c-49b1-a324-f49afe17a77b.png)

2022-06-01 06:43 UTC, mrosvik commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
@mjulstein 
Litt usikker på denne: 
`min-width: 9rem; /* TODO: get the token for this*/ `
Er det egentlig vits å ha med en min-width?

2022-06-08 17:55 UTC, haakemon commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
Den eneste grunnen jeg kan komme på for å ha noe slikt vil være for at knapper med forskjellig tekstlengde, men likevel hører sammen (f.eks "Forrige" og "Neste") skal se like store ut. Dette vil dog bare virke dersom teksten er kort nok til å være mindre enn min-width. 

@mrosvik det er altså ikke noe slikt krav at de skal være like store? For min del kan vi godt droppe dette 🙂

2022-06-10 06:14 UTC, mrosvik commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
@haakemon Det vil isåfall kun være relavant på små skjermer der tanken er at forrige/neste fyller ut 50% hver, slik: 
![image](https://user-images.githubusercontent.com/1464915/173002185-ba693087-414a-4115-a70c-49d6b63ac311.png)

2022-06-16 12:01 UTC, haakemon commented on src/components/Button/Button.module.css
> +  padding: 1rem 2.4rem 0.8rem 2.4rem; /* TODO: get the token for this */
Enig.

Forrige/Neste knapper som skal fylle 50% hver må løses i app-frontend.

2022-06-16 12:07 UTC, haakemon approved these changes

2022-06-16 12:07 UTC, merged